### ISSUE TITLE
Uncaught TypeError: Cannot read property 'isEmpty' of undefined

### ISSUE THREAD

**Issue by dharness** [mark-hahn/drag-drop-text#1]
[Enter steps to reproduce below:]
1. everywhere I click..
2. ...

**Atom Version**: 0.207.0
**System**: Mac OS X 10.10.2
**Thrown From**: [drag-drop-text](https://github.com/mark-hahn/drag-drop-text) package, v0.1.2
### Stack Trace

Uncaught TypeError: Cannot read property 'isEmpty' of undefined

```
At /Users/dharness/.atom/packages/drag-drop-text/lib/drag-drop-text.coffee:30

TypeError: Cannot read property 'isEmpty' of undefined
  at DragDropText.getSelection (/Users/dharness/.atom/packages/drag-drop-text/lib/drag-drop-text.coffee:30:20)
  at DragDropText.mousedown (/Users/dharness/.atom/packages/drag-drop-text/lib/drag-drop-text.coffee:39:6)
  at HTMLDivElement.<anonymous> (/Users/dharness/.atom/packages/drag-drop-text/lib/drag-drop-text.coffee:23:10)
  at HTMLDivElement.jQuery.event.dispatch (/Users/dharness/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4435:9)
  at HTMLDivElement.elemData.handle (/Users/dharness/Downloads/Atom.app/Contents/Resources/app.asar/node_modules/jquery/dist/jquery.js:4121:28)

```
### Commands

```
     -3:30.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -3:30.4.0 core:move-right (atom-text-editor.editor.is-focused)
     -3:30 core:move-left (atom-text-editor.editor.is-focused)
     -3:29.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -3:28.6.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
 28x -3:07.0 core:undo (atom-text-editor.editor.is-focused)
     -3:00.8.0 core:save (atom-text-editor.editor.is-focused)
     -2:54.8.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -2:54.2.0 core:save (atom-text-editor.editor.is-focused)
     -2:46.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -2:45.9.0 core:save (atom-text-editor.editor.is-focused)
  3x -2:42.9.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -2:37.8.0 core:cut (atom-text-editor.editor.is-focused)
     -2:37 core:paste (atom-text-editor.editor.is-focused)
     -2:36.6.0 core:save (atom-text-editor.editor.is-focused)
     -1:27.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".DS_Store"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.27.10
autocomplete-paths, v1.0.2
color-picker, v2.0.4
drag-drop-text, v0.1.2
file-icons, v1.5.7

# Dev
No dev packages
```

**Comment by mark-hahn** [comment]
Thanks a bunch.  Fixed in 0.1.3.
